# Generated by Django 5.2 on 2025-12-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
